//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    public Account()
    {
        this.Picture = new HashSet<Picture>();
        this.PictureCategory = new HashSet<PictureCategory>();
        this.PictureMainCategory = new HashSet<PictureMainCategory>();
        this.Article = new HashSet<Article>();
        this.ArticleCategory = new HashSet<ArticleCategory>();
        this.ArticleMainCategory = new HashSet<ArticleMainCategory>();
        this.Client = new HashSet<Client>();
        this.ClientCategory = new HashSet<ClientCategory>();
        this.Contact = new HashSet<Contact>();
        this.ContactCategory = new HashSet<ContactCategory>();
        this.Product = new HashSet<Product>();
        this.ProductCategory = new HashSet<ProductCategory>();
        this.ProductMainCategory = new HashSet<ProductMainCategory>();
        this.Staff = new HashSet<Staff>();
        this.StaffCategory = new HashSet<StaffCategory>();
        this.StaffMainCategory = new HashSet<StaffMainCategory>();
    }

    public string Username { get; set; }
    public string Password { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Mobi { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string AccountCategoryID { get; set; }

    public virtual ICollection<Picture> Picture { get; set; }
    public virtual ICollection<PictureCategory> PictureCategory { get; set; }
    public virtual ICollection<PictureMainCategory> PictureMainCategory { get; set; }
    public virtual AccountCategory AccountCategory { get; set; }
    public virtual ICollection<Article> Article { get; set; }
    public virtual ICollection<ArticleCategory> ArticleCategory { get; set; }
    public virtual ICollection<ArticleMainCategory> ArticleMainCategory { get; set; }
    public virtual ICollection<Client> Client { get; set; }
    public virtual ICollection<ClientCategory> ClientCategory { get; set; }
    public virtual ICollection<Contact> Contact { get; set; }
    public virtual ICollection<ContactCategory> ContactCategory { get; set; }
    public virtual ICollection<Product> Product { get; set; }
    public virtual ICollection<ProductCategory> ProductCategory { get; set; }
    public virtual ICollection<ProductMainCategory> ProductMainCategory { get; set; }
    public virtual ICollection<Staff> Staff { get; set; }
    public virtual ICollection<StaffCategory> StaffCategory { get; set; }
    public virtual ICollection<StaffMainCategory> StaffMainCategory { get; set; }
}

public partial class AccountCategory
{
    public AccountCategory()
    {
        this.Account = new HashSet<Account>();
    }

    public string AccountCategoryID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }

    public virtual ICollection<Account> Account { get; set; }
}

public partial class Article
{
    public int ArticleID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Content { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public string SourcePage { get; set; }
    public string SourceLink { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> ArticleCategoryID { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ArticleCategory ArticleCategory { get; set; }
}

public partial class ArticleCategory
{
    public ArticleCategory()
    {
        this.Article = new HashSet<Article>();
    }

    public int ArticleCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> ArticleMainCategoryID { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Article> Article { get; set; }
    public virtual ArticleMainCategory ArticleMainCategory { get; set; }
}

public partial class ArticleMainCategory
{
    public ArticleMainCategory()
    {
        this.ArticleCategory = new HashSet<ArticleCategory>();
    }

    public int ArticleMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<ArticleCategory> ArticleCategory { get; set; }
}

public partial class Client
{
    public Client()
    {
        this.Order = new HashSet<Order>();
    }

    public int ClientID { get; set; }
    public string Code { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string FullName { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Mobi { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string ApproveBy { get; set; }
    public Nullable<int> ClientCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ClientCategory ClientCategory { get; set; }
    public virtual ICollection<Order> Order { get; set; }
}

public partial class ClientCategory
{
    public ClientCategory()
    {
        this.Client = new HashSet<Client>();
    }

    public int ClientCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Client> Client { get; set; }
}

public partial class Contact
{
    public int ContactID { get; set; }
    public string Code { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string Mobi { get; set; }
    public string Content { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string ApproveBy { get; set; }
    public Nullable<int> ContactCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ContactCategory ContactCategory { get; set; }
}

public partial class ContactCategory
{
    public ContactCategory()
    {
        this.Contact = new HashSet<Contact>();
    }

    public int ContactCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Contact> Contact { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.OrderDetail = new HashSet<OrderDetail>();
    }

    public int OrderID { get; set; }
    public string Code { get; set; }
    public Nullable<double> Total { get; set; }
    public string Email { get; set; }
    public string FullName { get; set; }
    public string Mobi { get; set; }
    public string Mobi2 { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<int> PaymentMethod { get; set; }
    public string Comment { get; set; }
    public Nullable<bool> OrderStatus { get; set; }
    public Nullable<bool> DeliverStatus { get; set; }
    public Nullable<bool> ChargeStatus { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> ClientID { get; set; }
    public Nullable<int> StaffID { get; set; }

    public virtual Client Client { get; set; }
    public virtual Staff Staff { get; set; }
    public virtual ICollection<OrderDetail> OrderDetail { get; set; }
}

public partial class OrderDetail
{
    public int OrderID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<double> Price { get; set; }

    public virtual Order Order { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Picture
{
    public int PictureID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> PictureCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual PictureCategory PictureCategory { get; set; }
}

public partial class PictureCategory
{
    public PictureCategory()
    {
        this.Picture = new HashSet<Picture>();
    }

    public int PictureCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> PictureMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Picture> Picture { get; set; }
    public virtual PictureMainCategory PictureMainCategory { get; set; }
}

public partial class PictureMainCategory
{
    public PictureMainCategory()
    {
        this.PictureCategory = new HashSet<PictureCategory>();
    }

    public int PictureMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<PictureCategory> PictureCategory { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.OrderDetail = new HashSet<OrderDetail>();
    }

    public int ProductID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Content { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public string GalleryImageList { get; set; }
    public string SourcePage { get; set; }
    public string SourceLink { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<double> Price { get; set; }
    public Nullable<double> OldPrice { get; set; }
    public string Promotions { get; set; }
    public string WarrantyPolicy { get; set; }
    public string Specifications { get; set; }
    public string Accessories { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    public virtual ProductCategory ProductCategory { get; set; }
}

public partial class ProductCategory
{
    public ProductCategory()
    {
        this.Product = new HashSet<Product>();
    }

    public int ProductCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Product> Product { get; set; }
    public virtual ProductMainCategory ProductMainCategory { get; set; }
}

public partial class ProductMainCategory
{
    public ProductMainCategory()
    {
        this.ProductCategory = new HashSet<ProductCategory>();
    }

    public int ProductMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<ProductCategory> ProductCategory { get; set; }
}

public partial class Staff
{
    public Staff()
    {
        this.Order = new HashSet<Order>();
    }

    public int StaffID { get; set; }
    public string Code { get; set; }
    public string AcademicTitles { get; set; }
    public string FullName { get; set; }
    public string Specialize { get; set; }
    public string Email { get; set; }
    public string Mobi { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string WorkSchedule { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> StaffCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Order> Order { get; set; }
    public virtual StaffCategory StaffCategory { get; set; }
}

public partial class StaffCategory
{
    public StaffCategory()
    {
        this.Staff = new HashSet<Staff>();
    }

    public int StaffCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> StaffMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Staff> Staff { get; set; }
    public virtual StaffMainCategory StaffMainCategory { get; set; }
}

public partial class StaffMainCategory
{
    public StaffMainCategory()
    {
        this.StaffCategory = new HashSet<StaffCategory>();
    }

    public int StaffMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<StaffCategory> StaffCategory { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
