//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DBEntities : DbContext
{
    public DBEntities()
        : base("name=DBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Account> Account { get; set; }
    public DbSet<AccountCategory> AccountCategory { get; set; }
    public DbSet<Article> Article { get; set; }
    public DbSet<ArticleCategory> ArticleCategory { get; set; }
    public DbSet<ArticleMainCategory> ArticleMainCategory { get; set; }
    public DbSet<Client> Client { get; set; }
    public DbSet<ClientCategory> ClientCategory { get; set; }
    public DbSet<Contact> Contact { get; set; }
    public DbSet<ContactCategory> ContactCategory { get; set; }
    public DbSet<Order> Order { get; set; }
    public DbSet<OrderDetail> OrderDetail { get; set; }
    public DbSet<Picture> Picture { get; set; }
    public DbSet<PictureCategory> PictureCategory { get; set; }
    public DbSet<PictureMainCategory> PictureMainCategory { get; set; }
    public DbSet<Product> Product { get; set; }
    public DbSet<ProductCategory> ProductCategory { get; set; }
    public DbSet<ProductMainCategory> ProductMainCategory { get; set; }
    public DbSet<Staff> Staff { get; set; }
    public DbSet<StaffCategory> StaffCategory { get; set; }
    public DbSet<StaffMainCategory> StaffMainCategory { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
}
